### ISSUE TITLE
Repo warning and pip use on Tails

### ISSUE THREAD

**Issue by AnonymousAard** [pjkundert/python-slip39#1]

**Comment by AnonymousAard** [comment]
Thank you for sharing this.

There is warning on the repo: failed to load latest commit information, and Tails (with confirmed Internet access) does not allow pip install and errors on temporary failure in name resolution.

**Comment by pjkundert** [comment]
I'll be updating the project soon; lets close this 'til that is complete and see if there's still an issue.
