### ISSUE TITLE
MacOS App: Support 2 Group Minimum 

### ISSUE THREAD

**Issue by emailchaos** [pjkundert/python-slip39#5]
4 groups is a sane default. Consider allowing as little as 2 groups in MacOS UI (group removal).

**Comment by pjkundert** [comment]
It does allow group removal in the GUI; erase the name (backspace), and the row will disappear the next time the UI refreshes (for example, just re-select the "Controls" radio button at the top of the UI).

Not "discoverable", I know: I'm not a UI designer, obviously!  :)
