### ISSUE TITLE
Use m/49' instead of m/44' for SegWit addresses

### ISSUE THREAD

**Issue by fdegros** [pjkundert/python-slip39#9]
This `slip39` tool uses a derivation path starting with `m/44'` for both legacy and SegWit addresses, for both BTC and LTC. This is different from other major wallets, which use `m/49'` for SegWit addresses. Is this discrepancy an oversight, or a deliberate design decision?

**Comment by pjkundert** [comment]
Thanks for finding this; sorry I have taken so long to get to it!  I'll be integrating some of your changes into the development branch ASAP!

**Comment by fdegros** [comment]
No worries. Let me know if you have any question.
